your_name = input('What is your name? ')
your_age = input('What is your age? ')
your_place = input('Where do you live? ')
your_school = input('Which school do you study? ')
print('Your name is ' + your_name + ' your age is ' + your_age + ' you live in ' + your_place + ' you study in ' + your_school + '"If you read this you are waste"')